### ISSUE TITLE
Removing labels as part of config file

### ISSUE THREAD

**Issue by antonelli** [carrot/ash-github#18]
I would like to remove some of the existing default labels that are automatically added when you create a new repo. Something like...

``` md
# unwanted labels
delete:invalid
delete:question
delete:wontfix

# qa status
not-a-bug:e6e6e6
...
```

Or alternatively, a `--clear-labels` flag when running could be useful - but risky if you run it by mistake.

**Comment by BrandonRomano** [comment]
@antonelli I definitely like this idea!

Perhaps so we prevent any ambiguous syntax, we should also prefix the ones we are adding with `add` (You can imagine a conflict where a user might want a tag named `delete`).

I am leaning towards:

```
delete:invalid
add:not-a-bug:e6e6e6
```

or

```
delete:invalid
add:not-a-bug/e6e6e6
```

Any preferences?  I think the `/` is more readable.

**Comment by antonelli** [comment]
I wouldn't want to drop support for the current label config files if possible. What about a dash to denote that it's an action and not a label?

```
# delete the `invalid` label
-delete:invalid

# create the `delete` label
delete:000000
```

**Comment by BrandonRomano** [comment]
Great idea.  I'll do that
