### ISSUE TITLE
Rename repo to ghrepo

### ISSUE THREAD

**Issue by BrandonRomano** [carrot/ash-github#2]
This project will pretty only manage Github repos, and it seems more fluent to do `ash ghrepo:labels`.

**Comment by BrandonRomano** [comment]
@kylemac, thoughts?

**Comment by BrandonRomano** [comment]
(assigned it to you just to get your thoughts, I'll do the renaming if agree)

**Comment by kylemac** [comment]
i prefer `ghtools`

**Comment by BrandonRomano** [comment]
Okay, I think I'll side with you... More flexible :cat:
