### ISSUE TITLE
Carrots Mobile

### ISSUE THREAD

**Issue by BrandonRomano** [carrot/ash-github#25]
@antonelli I believe we can take your entire `Carrots - iOS` with the exceptions of the `# issue platform` section?

Also, would love to add into `# dev action` `implement:fbca04`.  I usually use this label to let people know that an issue is ready to start development on.

If you're in agreement, I can do this for us

**Comment by BrandonRomano** [comment]
Assigning to you just for feedback, not to actually implement (unless you want to)

**Comment by antonelli** [comment]
Hmm. `implement` feels a little too open ended to me. Usually I see open issues as a sign that they should be or are being worked on, and if not then a 'blocked' or 'on-hold' label identifies it as otherwise.

**Comment by BrandonRomano** [comment]
Alright yeah I think I can update my workflow to do that then... You're right it is very open ended, and most issues actually have that tag :cat: 

I'll use on-hold
